version: "3.9"
services:
  shop:
    build: ./shop
    ports:
      - "8000:5000"
    environment:
      - MONGO_USER=root
      - MONGO_PASS=password
      - PYTHONUNBUFFERED=1
  talks:
    build: ./lfi
    ports:
      - "3000:5000"
    environment:
      - MONGO_USER=root
      - MONGO_PASS=password
      - PYTHONUNBUFFERED=1
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  registry:
    build: ./docker-registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    #   - ./docker-registry/auth:/auth
    restart: always
    container_name: registry

